import { University } from "@/assets";

const UniversityData = [
  {
    id: 1,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 2,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 3,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 4,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 5,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 6,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 7,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 8,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 9,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 10,
    University_Id: "#20207",
    University_Img: University,
    University_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
];

const InstituteData = [
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  {
    id: 1,
    Institute_Id: "#20207",
    University: "Mumbai University",
    Institute_Img: University,
    Institute_Name: "Avatar",
    Registered_On: "2/10/2024",
  },
  
];

const AluminiData = [
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  {
    id: 1,
    Rank:20,
    Alumini_Img: University,
    University: "Mumbai University",
    Institute_Name: "Avatar",
    Gr_No: "21051",
  },
  
];

export { UniversityData, InstituteData, AluminiData };
